# Generated by Django 5.1.5 on 2025-02-11 22:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_user_phone_number_alter_user_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Awards",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sub_category",
                    models.TextField(default="Should FK to sub categories table"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="api_awards_name_9e842c_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Nominees",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("image", models.URLField(default="NA")),
                ("votes", models.IntegerField(default=0)),
                ("share_link", models.URLField(default="NA")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.awards"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="api_nominee_name_6b4150_idx")
                ],
            },
        ),
    ]
