# Generated by Django 5.1.5 on 2025-02-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awards",
            name="sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.subcategory"
            ),
        ),
    ]
