# Generated by Django 5.1.5 on 2025-02-15 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_awards_sub_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Votes",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nominee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.nominees"
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.subcategory",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["ID"], name="api_votes_ID_721f4f_idx")
                ],
            },
        ),
    ]
