# Generated by Django 5.1.5 on 2025-02-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_0004_subcategory_0007_votes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nominees',
            name='api_nominee_name_6b4150_idx',
        ),
        migrations.RenameField(
            model_name='nominees',
            old_name='description',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='nominees',
            old_name='category_ID',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='nominees',
            old_name='ID',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='nominees',
            name='name',
        ),
        migrations.RemoveField(
            model_name='nominees',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='nominees',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominees',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominees',
            name='last_name',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominees',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nominees',
            name='stage_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='votes',
            name='nominee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.nominees'),
        ),
        migrations.AddIndex(
            model_name='nominees',
            index=models.Index(fields=['id'], name='api_nominee_id_b978e3_idx'),
        ),
    ]
