# Generated by Django 5.1.5 on 2025-02-21 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_nominees_api_nominee_name_6b4150_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominees',
            name='sub_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.subcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nominees',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
