from collections import Counter

# Sample data: voting list  
votes = [
    "Nominee A", "Nominee B", "Nominee A", "Nominee C",
    "Nominee B", "Nominee A", "Nominee C", "Nominee C",
    "Nominee A", "Nominee B"
]

# Using Counter to count votes
vote_count = Counter(votes)

# Displaying the results
print("voting results :")
for nominee, count in vote_count.items():
    print(f"{nominee}: {count} votes")

# Trouver le gagnant
winner = vote_count.most_common(1)[0]
print(f"\nLe gagnant est {winner[0]} avec {winner[1]} votes !")
